### ISSUE TITLE
Handle scale in hierarchy

### ISSUE THREAD

**Issue by nem0** [nem0/LumixEngine#1129]

**Comment by timbaker** [comment]
This issue is affecting me now that I've parented the player to another object (a vehicle with scale < 1.0).
After a few calls to setLocalRotation(camera_entity, rot), the camera's scale blows up.

It would be nice if the scale set in the editor was not changed by parenting or by changing the scale of an ancestor.  It seems entities would need a scale set in the editor, and a different scale affected by heirarchy.

**Comment by nem0** [comment]
Please try with the latest revision

**Comment by timbaker** [comment]
I'm using the latest 'master' branch if that's what you mean.
You can see the problem by creating 3 entities A, B, C with cube.msh.
Make A parent of B, then B parent of C, and see what happens when the scale of A is changed.

**Comment by nem0** [comment]
I'm sorry, I commited to wrong branch, it's in master now

**Comment by nem0** [comment]
I've managed to reproduce the bug with your instructions, working on it

**Comment by nem0** [comment]
Should be ok now

**Comment by timbaker** [comment]
Perhaps this will show the bug better.  There are 3 boxes, A, B and C.  Select 'B' then click in the "Location Position" X field.  Even without dragging the mouse, the scale of B and C starts changing rapidly.





[ScaleBug.zip](https://github.com/nem0/LumixEngine/files/1232950/ScaleBug.zip)

**Comment by nem0** [comment]
Fixed

**Comment by timbaker** [comment]
Great, it all seems to be working fine now.
