### ISSUE TITLE
graphics glitches in studio.exe

### ISSUE THREAD

**Issue by kungfooman** [nem0/LumixEngine#1250]
Hi, is this a known issue or something? Just wanted to test this again, but got lots of graphics glitches: https://youtu.be/dSIzRDEaFpM

Last time some months ago I tested on same hardware without any bugs, but I built it myself in Visual Studio

**Comment by nem0** [comment]
I've never seen that. Could you try deleting ```pipelines/compiled```?

**Comment by Alan-FGR** [comment]
I've seen something like that with bad drivers... don't remember if it was nvidia or intel gpu though.

**Comment by kungfooman** [comment]
Thanks for the input, I tried deleting `pipelines/compiled` and it recompiled all shaders, but still the same glitches

My GPU is AMD Radeon R9 390

Driver info in hardware manager:
Advanced Micro Devices, Inc.
Driver date: 22/09/2017
Driver version: 22.19.677.257

I have no problems with any other 3D software/games and I tested quite some, also BGFX related (BGFX renderer for ioquake3 e.g.)

**Comment by Alan-FGR** [comment]
I noticed that the viewport also glitches, so depending on how lumix is displaying that (i.e.: if imgui is handling that or not) it could also be a problem with the imgui draw data (I was having a very similar problem recently with imgui draw data btw, but it was, my fault :laughing:).
Perhaps it's worth giving a try on the bgfx examples of the same version lumix is using, @nem0 will be able to help with that since it's not a git submodule and there's no version info in `external/bgfx/include/bgfx` so I don't know what commit it is.
That being said, isn't that driver a little bit outdated? Even if it's not related to this problem it's always better to keep your drivers updated in general.

@nem0 new renderer going well? :trollface:

**Comment by Kenji245** [comment]
have you updated the [LumixEngine_Data](https://github.com/nem0/lumixengine_data) repository?

**Comment by kungfooman** [comment]
@Alan-FGR Thanks for the idea, I did that now.

You can see the bgfx version here: https://github.com/nem0/LumixEngine_3rdparty/tree/master/3rdparty

I built the examples for this lumix bgfx version and every example project I tested worked nicely (dragged around imgui windows etc.)

@Kenji245 Yea, it was the latest master snapshot

I tried to completely build LumixEngine now (with 3rdparty libs), but I get this assertion:

![90dbdaf77818b293fafbc16b859a4543](https://user-images.githubusercontent.com/5236548/42298109-73ac8410-8004-11e8-8914-c6724c3f6008.png)

It is called twice, first time is success, the second time it fails

When I keep going with F5, studio.exe is starting, but it is just a gray window.

Kinda out of ideas

**Comment by nem0** [comment]
that should be fixed now

**Comment by kungfooman** [comment]
thanks, now im running into shader compile errors: https://gist.github.com/kungfooman/0282cb38c1af9c1b70a68f0f2b1ab6b9

i also tried the `-opengl` command line option for testing, but both fails

**Comment by nem0** [comment]
that looks like if you checkout the data with wrong lineendings

**Comment by nem0** [comment]
Lumix switched to completely new renderer, so this should not happen anymore.
