### ISSUE TITLE
Race conditions in asset recompiling

### ISSUE THREAD

**Issue by jdswebb** [nem0/LumixEngine#1296]
It's pretty hard to repro this sometimes. But there seem to be some issues with asset re-compiling.

I've had the following happen:

1. Due to FileSystemWatcher emitting multiple reloads for the same file, the following can happen:
- The first reload unloads the resource successfully then queues up an async reload
- updateAsyncTransactions() starts loading the file but at the same time the second reload starts
- This can result in Resource::doUnload() and Resource::fileLoaded() being called on the same resource at the same time in different threads which leads to an invalid state.

2.  Crashes due to an asset being reloaded while in use. This happens if say a condition like 'if (m_shader->isReady())' passes, so the render code starts using it, but then the FileSystemWatcher starts reloading it due to an external change.

Thanks

**Comment by nem0** [comment]
Hi, thanks for the report. This should be fixed in new_anim branch 
https://github.com/nem0/LumixEngine/blob/32bc4d28c84ded0cd6ae2781d49518b29b44efeb/src/editor/asset_compiler.cpp#L372 became https://github.com/nem0/LumixEngine/blob/d90d42dc18ed181a3f73a76ee5210f3fc7cad74b/src/editor/asset_compiler.cpp#L373

**Comment by jdswebb** [comment]
Ah nice, I'll test it out - thanks!

**Comment by jdswebb** [comment]
👍
