### ISSUE TITLE
Crash in nvoglv64

### ISSUE THREAD

**Issue by divinon** [nem0/LumixEngine#1317]
Hello nemo, I have a crash in OpenGL:
`Exception thrown at 0x00000000530D6E60 (nvoglv64.dll) in studio.exe: 0xC0000005: Access violation reading location 0x0000000000000000.`

This happens in: drawArray -> gpu::drawArrays
It goes away if I comment out renderLightProbeGrids in the pipeline, the drawArray crashing is just few lines later, or if I add another random attribute to m_3D_pos_decl or remove its only float3 attribute.
Only happens in ReleaseWithDebugInfo, not in Debug, maybe Debug fills memory with something which OpenGL likes.
Do you have any pointers? Drivers? VS2017(mine) vs VS2019? 

Also in "BOOL SendFile()" at "strcat_s(szText, lpszText);" szText can be too small for lpszText.

**Comment by nem0** [comment]
Thanks for the report, I can reproduce it. It does not crash in debug because  opengl debug logging is enabled. One must love OpenGL drivers :) 
strcat_s should be safe according to https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strcat-s-wcscat-s-mbscat-s?view=vs-2019 but you are right, that code could be improved.

**Comment by divinon** [comment]
You are right, strcat_s is the macro-magic __DEFINE_CPP_OVERLOAD_SECURE_FUNC_0_1 which should get the size right, but for me it crashes somehow with a string of 356 bytes. I though about the size but it could be something else.
