### ISSUE TITLE
missing sphere implementaition for lua 

### ISSUE THREAD

**Issue by p1plp1** [nem0/LumixEngine#1347]
missing sg like Lumix::PipelineImpl::drawSphere for lua scripting:

drawSphere( Vector position, number radius, number longitudeSteps, number latitudeSteps, table color = Color( 255, 255, 255 ) )
drawSphere( Vector position, number radius, number longitudeSteps, number latitudeSteps, material Material )

**Comment by nem0** [comment]
Hi, I've added addDebugTriangle in 2fa8c7b200e0839eb4c40e5aee020eb92f2a56ec so you can build any shape you want with it. This is intended just for debug purpose. If want to create procedural geometry, there's no API for that right now in Lua. I can expose something, but since it probably needs to be fast, it's better to use c++ for that.
