### ISSUE TITLE
Fully integrate SDL

### ISSUE THREAD

**Issue by nem0** [nem0/LumixEngine#860]

**Comment by nem0** [comment]
It turned out using SDL causes more problems than it solves, even though it's a great library. For example: it has   only 32bit atomics and Lumix requires 64bit too, or it is not possible to set thread's stack size in SDL.

**Comment by ongamex** [comment]
Although it's totally unrelated, I've a few points in favor of "no SDL"(taken from my experience). SDL depends on few deprecated libraries from DirectXSDK Jun2010 in order to support direct input, and could possibly lead to errors if those libraries are mixed with the currently official DirectX SDK.
Additionally it is a nightmare to build the library yourself.

**Comment by nem0** [comment]
@ongamex I stopped using it further and I will probably replace it completely in some time. It's a nice library and it serves it purpose, but I do not like using 3rd party libs and keeping it here just to handle a window is unnecessary.
