### ISSUE TITLE
Bullet Physics plugin

### ISSUE THREAD

**Issue by nem0** [nem0/LumixEngine#872]

**Comment by luchete80** [comment]
Since i'm interested in soft physics and for that i prefer bullet without any doubt, together with pbr branch i'm begining a branch with bullet plugin for lumix. I hope this helps.

[https://github.com/luchete80/LumixEngine/tree/bullet](url)

**Comment by nem0** [comment]
:+1: 
I plan to have Bullet plugin in separate repository and here as a git submodule. And maybe later if Bullet proves to be better than PhysX, Bullet can be directly in the main repo and PhysX as a submodule.

**Comment by VinnyVicious** [comment]
Another interesting project: https://projectchrono.org/

**Comment by nem0** [comment]
@VinnyVicious Looks nice, is anybody using it?

**Comment by Alan-FGR** [comment]
I've used project Chrono, and it's an awesome project but it's not really suitable for games, it only uses the Bullet lib for collision detection and the solvers are focused on accuracy and aren't optimized for speed at all. I've used it for structural analysis because there's a lack of libs for that supporting nonlinear FEA, so Chrono was a somewhat decent kinda ugly workaround for that. But it's an engineering lib.
Also, I totally don't recommend spending any efforts in a Bullet plugin... c'mon guys, PhysX is superior in every single aspect, generally people avoid PhysX because of licensing or 'moral' reasons, if that's not a concern, then it's a nobrainer.

**Comment by VinnyVicious** [comment]
It makes no sense for a FOSS engine to use non-FOSS libraries.

**Comment by Alan-FGR** [comment]
It's free for commercial use without restrictions, in my opinion what doesn't make sense is not using the best lib around because of software ideology.

**Comment by nem0** [comment]
@Alan-FGR One reason to spend some effort on Bullet is that PhysX is off putting many users and they will not use the engine just because of it. Anyway, PhysX will probably always be the default physics plugin for Lumix, but anyone who mind that can use Bullet, once it's implemented.

**Comment by VinnyVicious** [comment]
Why use less-featured engine with 10% of all the middleware that you can find on engines like Unreal? Because freedom matters. Having all four freedoms matter. Software ideology matters.

**Comment by Alan-FGR** [comment]
Which freedom exactly is the PhysX license restricting? Just because it's not OSI-approved it doesn't mean it's "evil". UE4 license on the other hand is quite restrictive, what in many cases is reason enough not to use it (it's expensive, especially for studios). The fact is, from a legal standpoint there's not much difference, but from a technical standpoint PhysX is much better. As far as I know @nem0 wants an engine that can compete in the market, in which having a good product matters much more than any software ideology. You can't live from software freedom activism like rms.

**Comment by boberfly** [comment]
Just to note, Bullet 2.x recently pulled in a bunch of PRs which solves multi-threading issues (in the past it had it and then it was disabled to single-threading only), you need to supply it a job work queue of sorts though.

This might solve the performance gap to an extent, and probably 3.x will probably bring it more towards the GPU-side of PhysX. But yeah, I guess for the other neat things PhysX brings outside of collisions and dynamics wouldn't be available, but these aren't exposed in Lumix though.

**Comment by nem0** [comment]
https://github.com/nem0/LumixEngine/wiki/Available-plugins
